(function(){var h={},mt={},c={id:"350d834e9b212adee92daa5ed888a2e7",dm:["incake.net"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:2617165,qiao:0,lxb:0,conv:0,apps:''};var p=!0,q=null,r=!1;mt.j={};mt.j.Ga=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.j.cookieEnabled=navigator.cookieEnabled;mt.j.javaEnabled=navigator.javaEnabled();mt.j.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.j.ra=(window.screen.width||0)+"x"+(window.screen.height||0);mt.j.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,b,d){var e;d.D&&(e=new Date,e.setTime(e.getTime()+d.D));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(e?"; expires="+e.toGMTString():"")+(d.Ka?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.p={};mt.p.ca=function(a){return document.getElementById(a)};mt.p.Da=function(a,b){for(b=b.toUpperCase();(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return q};
(mt.p.R=function(){function a(){if(!a.t){a.t=p;for(var b=0,d=e.length;b<d;b++)e[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(b,1);return}a()}var d=r,e=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,r);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!d)if(d=p,"complete"===document.readyState)a.t=p;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
g,r),window.addEventListener("load",a,r);else if(document.attachEvent){document.attachEvent("onreadystatechange",g);window.attachEvent("onload",a);var e=r;try{e=window.frameElement==q}catch(n){}document.documentElement.doScroll&&e&&b()}})();return function(b){a.t?b():e.push(b)}}()).t=r;mt.event={};mt.event.d=function(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(e){d.call(a,e)}):a.addEventListener&&a.addEventListener(b,d,r)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=r};mt.n={};mt.n.parse=function(){return(new Function('return (" + source + ")'))()};
mt.n.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return a(e);case "boolean":return String(e);
default:if(e===q)return"null";if(e instanceof Array){var d=["["],m=e.length,n,f,k;for(f=0;f<m;f++)switch(k=e[f],typeof k){case "undefined":case "function":case "unknown":break;default:n&&d.push(","),d.push(mt.n.stringify(k)),n=1}d.push("]");return d.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+b(e.getMonth()+1)+"-"+b(e.getDate())+"T"+b(e.getHours())+":"+b(e.getMinutes())+":"+b(e.getSeconds())+'"';n=["{"];f=mt.n.stringify;for(m in e)if(Object.prototype.hasOwnProperty.call(e,m))switch(k=
e[m],typeof k){case "undefined":case "unknown":case "function":break;default:d&&n.push(","),d=1,n.push(f(m)+":"+f(k))}n.push("}");return n.join("")}}}();mt.lang={};mt.lang.e=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ha=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.Ja=function(a){return mt.lang.e(a,"String")};mt.localStorage={};
mt.localStorage.B=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return r}return p};
mt.localStorage.set=function(a,b,d){var e=new Date;e.setTime(e.getTime()+d||31536E6);try{window.localStorage?(b=e.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.B()&&(mt.localStorage.f.expires=e.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,b),mt.localStorage.f.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.B())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(e){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.B())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){if(window.sessionStorage)try{window.sessionStorage.setItem(a,b)}catch(d){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.S={};mt.S.log=function(a,b){var d=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=q;d=window[e]=q;b&&b(a)};d.src=a};mt.A={};
mt.A.ha=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return a};
mt.A.Y=function(a,b,d,e,g){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+d+'" height="'+e+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(g||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+d+'" height="'+e+'" src="'+b+'" flashvars="'+(g||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.h=function(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:q};mt.url.Fa=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.ea=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.M=function(a){return(a=mt.url.ea(a))?a.replace(/:\d+$/,""):a};mt.url.Ea=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.k={oa:"http://tongji.baidu.com/hm-web/welcome/ico",Q:"hm.baidu.com/hm.gif",V:"baidu.com",la:"hmmd",ma:"hmpl",ka:"hmkw",ia:"hmci",na:"hmsr",o:0,g:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",Ia:0,za:6E5,Aa:10,Ba:1024,ya:1,w:2147483647,T:"cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={l:{},d:function(a,d){this.l[a]=this.l[a]||[];this.l[a].push(d)},r:function(a,d){this.l[a]=this.l[a]||[];for(var e=this.l[a].length,g=0;g<e;g++)this.l[a][g](d)}};return h.m=a})();
(function(){function a(a,e){var g=document.createElement("script");g.charset="utf-8";b.e(e,"Function")&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=q,e()}:g.onload=function(){e()});g.src=a;var m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(g,m)}var b=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?d.set("Hm_from_"+c.id,a):b.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?d.get("Hm_from_"+c.id):b.get("Hm_from_"+c.id))||"";return a}var b=mt.localStorage,d=mt.sessionStorage;return h.K=a})();
(function(){var a=h.k,b=mt.A,d={init:function(){if(""!==c.icon){var d;d=c.icon.split("|");var g=a.oa+"?s="+c.id,m=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+d[0]+"."+d[1];switch(d[1]){case "swf":d=b.Y("HolmesIcon"+a.g,m,d[2],d[3],"s="+g);break;case "gif":d='<a href="'+g+'" target="_blank"><img border="0" src="'+m+'" width="'+d[2]+'" height="'+d[3]+'"></a>';break;default:d='<a href="'+g+'" target="_blank">'+d[0]+"</a>"}document.write(d)}}};h.m.d("pv-b",d.init);return d})();
(function(){var a=mt.p,b=h.k,d=h.load,e=h.K;h.m.d("pv-b",function(){c.rec&&a.R(function(){for(var g=0,m=c.rp.length;g<m;g++){var n=c.rp[g][0],f=c.rp[g][1],k=a.ca("hm_t_"+n);if(f&&!(2==f&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*b.w),k=4==f?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+n,"rnd="+k].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+n,"from="+e(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
k].join("&"),d(k)}})})})();(function(){var a=h.k,b=h.load,d=h.K;h.m.d("pv-b",function(){if(c.trust&&c.vcard){var e=a.protocol+"//trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+d(),"rnd="+Math.round(Math.random()*a.w)].join("&");b(e)}})})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.C.fa()+","+h.C.da();h.b.i()}}function b(){clearTimeout(x);var a;w&&(a="visible"==document[w]);y&&(a=!document[y]);f="undefined"==typeof a?p:a;if((!n||!k)&&f&&l)v=p,s=+new Date;else if(n&&k&&(!f||!l))v=r,u+=+new Date-s;n=f;k=l;x=setTimeout(b,100)}function d(a){var k=document,d="";if(a in k)d=a;else for(var l=["webkit","ms","moz","o"],s=0;s<l.length;s++){var b=l[s]+a.charAt(0).toUpperCase()+a.slice(1);if(b in k){d=
b;break}}return d}function e(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))l="focus"==a.type||"focusin"==a.type?p:r,b()}var g=mt.event,m=h.m,n=p,f=p,k=p,l=p,t=+new Date,s=t,u=0,v=p,w=d("visibilityState"),y=d("hidden"),x;b();(function(){var a=w.replace(/[vV]isibilityState/,"visibilitychange");g.d(document,a,b);g.d(window,"pageshow",b);g.d(window,"pagehide",b);"object"==typeof document.onfocusin?(g.d(document,"focusin",e),g.d(document,"focusout",e)):(g.d(window,"focus",e),
g.d(window,"blur",e))})();h.C={fa:function(){return+new Date-t},da:function(){return v?+new Date-s+u:u}};m.d("pv-b",function(){g.d(window,"unload",a())});return h.C})();
(function(){var a=mt.lang,b=h.k,d=h.load,e={pa:function(e){if((void 0===window._dxt||a.e(window._dxt,"Array"))&&"undefined"!==typeof h.b){var m=h.b.F();d([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(m)].join(""),e)}},xa:function(d){if(a.e(d,"String")||a.e(d,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",d])}};return h.Z=e})();
(function(){function a(k){for(var l in k)if({}.hasOwnProperty.call(k,l)){var b=k[l];d.e(b,"Object")||d.e(b,"Array")?a(b):k[l]=String(b)}}function b(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var d=mt.lang,e=mt.n,g=h.k,m=h.m,n=h.Z,f={N:q,q:[],z:0,O:r,init:function(){f.c=0;f.N={push:function(){f.I.apply(f,arguments)}};m.d("pv-b",function(){f.$();f.aa()});m.d("pv-d",f.ba);m.d("stag-b",function(){h.b.a.api=f.c||f.z?f.c+"_"+f.z:""});m.d("stag-d",function(){h.b.a.api=
0;f.c=0;f.z=0})},$:function(){var a=window._hmt;if(a&&a.length)for(var d=0;d<a.length;d++){var b=a[d];switch(b[0]){case "_setAccount":1<b.length&&/^[0-9a-z]{32}$/.test(b[1])&&(f.c|=1,window._bdhm_account=b[1]);break;case "_setAutoPageview":if(1<b.length&&(b=b[1],r===b||p===b))f.c|=2,window._bdhm_autoPageview=b}}},aa:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var a=window._hmt;if(a&&a.length)for(var b=0,e=a.length;b<e;b++)d.e(a[b],
"Array")&&"_trackEvent"!==a[b][0]&&"_trackRTEvent"!==a[b][0]?f.I(a[b]):f.q.push(a[b]);window._hmt=f.N}},ba:function(){if(0<f.q.length)for(var a=0,b=f.q.length;a<b;a++)f.I(f.q[a]);f.q=q},I:function(a){if(d.e(a,"Array")){var b=a[0];if(f.hasOwnProperty(b)&&d.e(f[b],"Function"))f[b](a)}},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"==a[1].charAt(0)){f.c|=4;h.b.a.et=0;h.b.a.ep="";h.b.G?(h.b.a.nv=0,h.b.a.st=4):h.b.G=p;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=g.protocol+"//"+document.location.host+
a[1];f.O||(h.b.a.su=document.location.href);h.b.i();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<a.length&&(f.c|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=b(a[1])+"*"+b(a[2])+(a[3]?"*"+b(a[3]):"")+(a[4]?"*"+b(a[4]):""),h.b.i())},_setCustomVar:function(a){if(!(4>a.length)){var d=a[1],e=a[4]||3;if(0<d&&6>d&&0<e&&4>e){f.z++;for(var s=(h.b.a.cv||"*").split("!"),u=s.length;u<d-1;u++)s.push("*");s[d-1]=e+"*"+b(a[2])+"*"+b(a[3]);h.b.a.cv=s.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.qa("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"==a[1].charAt(0)?g.protocol+"//"+window.location.host+a[1]:a[1],f.O=p)},_trackOrder:function(b){b=b[1];d.e(b,"Object")&&(a(b),f.c|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=e.stringify(b),h.b.i())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])f.c|=32,h.b.a.et=93,h.b.a.ep=a,h.b.i()},_trackRTPageview:function(b){b=
b[1];d.e(b,"Object")&&(a(b),b=e.stringify(b),512>=encodeURIComponent(b).length&&(f.c|=64,h.b.a.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.e(b,"Object")){a(b);b=encodeURIComponent(e.stringify(b));var l=function(a){var b=h.b.a.rt;f.c|=128;h.b.a.et=90;h.b.a.rt=a;h.b.i();h.b.a.rt=b},t=b.length;if(900>=t)l.call(this,b);else for(var t=Math.ceil(t/900),s="block|"+Math.round(Math.random()*g.w).toString(16)+"|"+t+"|",u=[],v=0;v<t;v++)u.push(v),u.push(b.substring(900*v,900*v+900)),l.call(this,s+u.join("|")),
u=[]}},_setUserId:function(a){a=a[1];n.pa();n.xa(a)}};f.init();h.W=f;return h.W})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.G=r,this.init())}var b=mt.url,d=mt.S,e=mt.A,g=mt.lang,m=mt.cookie,n=mt.j,f=mt.localStorage,k=mt.sessionStorage,l=h.k,t=h.m;a.prototype={H:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length==a.length},P:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},s:function(a){for(var d=0;d<c.dm.length;d++)if(-1<
c.dm[d].indexOf("/")){if(this.P(a,c.dm[d]))return p}else{var f=b.M(a);if(f&&this.H(f,c.dm[d]))return p}return r},F:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.H(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},L:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.P(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},ga:function(){if(!document.referrer)return l.g-l.o>c.vdur?1:4;var a=
r;this.s(document.referrer)&&this.s(document.location.href)?a=p:(a=b.M(document.referrer),a=this.H(a||"",document.location.hostname));return a?l.g-l.o>c.vdur?1:4:3},getData:function(a){try{return m.get(a)||k.get(a)||f.get(a)}catch(b){}},setData:function(a,b,d){try{m.set(a,b,{domain:this.F(),path:this.L(),D:d}),d?f.set(a,b,d):k.set(a,b)}catch(e){}},qa:function(a){try{m.set(a,"",{domain:this.F(),path:this.L(),D:-1}),k.remove(a),f.remove(a)}catch(b){}},va:function(){var a,b,d,f,e;l.o=this.getData("Hm_lpvt_"+
c.id)||0;13==l.o.length&&(l.o=Math.round(l.o/1E3));b=this.ga();a=4!=b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){f=d.split(",");for(e=f.length-1;0<=e;e--)13==f[e].length&&(f[e]=""+Math.round(f[e]/1E3));for(;2592E3<l.g-f[0];)f.shift();e=4>f.length?2:3;for(1===a&&f.push(l.g);4<f.length;)f.shift();d=f.join(",");f=f[f.length-1]}else d=l.g,f="",e=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,l.g);d=l.g==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.s(document.location.href)&&
(""===document.referrer||this.s(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=f;this.a.lv=e},ua:function(){for(var a=[],b=0,d=l.T.length;b<d;b++){var f=l.T[b],e=this.a[f];"undefined"!=typeof e&&""!==e&&a.push(f+"="+encodeURIComponent(e))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},wa:function(){this.va();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=n.ra;this.a.cl=n.colorDepth+"-bit";
this.a.ln=n.language;this.a.ja=n.javaEnabled?1:0;this.a.ck=n.cookieEnabled?1:0;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=e.ha();this.a.v="1.0.85";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=b.h(a,l.la)||"";this.a.cp=b.h(a,l.ma)||"";this.a.cw=b.h(a,l.ka)||"";this.a.ci=b.h(a,l.ia)||"";this.a.cf=b.h(a,l.na)||""},init:function(){try{this.wa(),0===this.a.nv?this.ta():this.J(".*"),h.b=this,this.X(),
t.r("pv-b"),this.sa()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(l.protocol+"//"+l.Q+"?"+b.join("&"))}},sa:function(){function a(){t.r("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.G=p,this.a.et=0,this.a.ep="",this.i(a)):a()},i:function(a){var b=this;b.a.rnd=Math.round(Math.random()*l.w);t.r("stag-b");var f=l.protocol+"//"+
l.Q+"?"+b.ua();t.r("stag-d");b.U(f);d.log(f,function(d){b.J(d);g.e(a,"Function")&&a.call(b)})},X:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),f=-1<document.referrer.indexOf(l.V)?p:r,e=b.h(a,"jn"),k=/^heatlink$|^select$/.test(e);a&&(d.test(a)&&f&&k)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",l.protocol+"//"+c.js+e+".js?"+this.a.rnd),e=document.getElementsByTagName("script")[0],e.parentNode.insertBefore(a,
e))},U:function(a){var b=k.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");k.set("Hm_unsent_"+c.id,b)},J:function(a){var b=k.get("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?k.set("Hm_unsent_"+c.id,b):k.remove("Hm_unsent_"+c.id))},ta:function(){var a=this,b=k.get("Hm_unsent_"+
c.id);if(b)for(var b=b.split(","),f=function(b){d.log(l.protocol+"//"+decodeURIComponent(b).replace(/^https?:\/\//,""),function(b){a.J(b)})},e=0,g=b.length;e<g;e++)f(b[e])}};return new a})();
(function(){var a=mt.p,b=mt.event,d=mt.url,e=mt.n;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var g=+new Date,m=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},n=q;a.R(function(){n=+new Date});var f=function(){var a,b,f;f=m("navigation");b=m("request");f={netAll:b.start-f.start,netDns:m("domainLookup").value,netTcp:m("connect").value,srv:m("response").start-b.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:m("loadEvent").end-f.start};a=document.referrer;var k=q;b=q;if("www.baidu.com"===(a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[])[2])k=d.h(a,"qid"),b=d.h(a,"click_t");a=k;f.qid=a!=q?a:"";b!=q?(f.bdDom=n?n-b:0,f.bdRun=g-b):(f.bdDom=0,f.bdRun=0);h.b.a.et=87;h.b.a.ep=e.stringify(f);h.b.i()};b.d(window,"load",function(){setTimeout(f,500)})}}catch(k){}})();
(function(){var a=h.k,b={init:function(){try{if("http:"===a.protocol){var b=document.createElement("IFRAME");b.setAttribute("src","http://boscdn.bpc.baidu.com/v1/holmes-moplus/mp-cdn.html");b.style.display="none";b.style.width="1";b.style.height="1";b.Ca="0";document.body.appendChild(b)}}catch(e){}}};-1<navigator.userAgent.toLowerCase().indexOf("android")&&b.init()})();
(function(){if("378f3aa9b8779062c8de4dc247dd8874"===c.id){var a=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},b={click:function(){for(var b=[],d=a(document.getElementsByTagName("a")),d=[].concat.apply(d,a(document.getElementsByTagName("area"))),e=/openZoosUrl\(/,g=0,m=d.length;g<m;g++)e.test(d[g].getAttribute("onclick"))&&b.push(d[g]);return b}},d=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===r)return r},e=function(a,
b){return Object.prototype.toString.call(a)==="[object "+b+"]"};window._hmt=window._hmt||[];var g,m="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),n=function(a,b){if(g===b){window._hmt.push(["_trackPageview",m+a]);for(var d=+new Date;500>=+new Date-d;);return r}if(e(b,"Array")||e(b,"NodeList"))for(var d=0,n=b.length;d<n;d++)if(g===b[d]){window._hmt.push(["_trackPageview",m+a+"/"+(d+1)]);for(d=+new Date;500>=+new Date-d;);return r}};(function(a,b,d){a.addEventListener?a.addEventListener(b,d,p):a.attachEvent&&
a.attachEvent("on"+b,d)})(document,"click",function(a){a=a||window.event;g=a.target||a.srcElement;var k={};for(d(b,function(a,b){k[a]=e(b,"Function")?b():document.getElementById(b)});g&&g!==document&&d(k,n)!==r;)g=g.parentNode})}})();})();
