(function(){var h={},mt={},c={id:"350d834e9b212adee92daa5ed888a2e7",dm:["incake.net"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:2617165,qiao:0,lxb:0,conv:0,apps:''};var p=!0,q=null,r=!1;mt.j={};mt.j.Da=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.j.cookieEnabled=navigator.cookieEnabled;mt.j.javaEnabled=navigator.javaEnabled();mt.j.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.j.qa=(window.screen.width||0)+"x"+(window.screen.height||0);mt.j.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,d,f){var b;f.D&&(b=new Date,b.setTime(b.getTime()+f.D));document.cookie=a+"="+d+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(b?"; expires="+b.toGMTString():"")+(f.Ha?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.q={};mt.q.ca=function(a){return document.getElementById(a)};mt.q.Aa=function(a,d){for(d=d.toUpperCase();(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return q};
(mt.q.T=function(){function a(){if(!a.w){a.w=p;for(var d=0,f=b.length;d<f;d++)b[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var f=r,b=[],l;document.addEventListener?l=function(){document.removeEventListener("DOMContentLoaded",l,r);a()}:document.attachEvent&&(l=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",l),a())});(function(){if(!f)if(f=p,"complete"===document.readyState)a.w=p;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
l,r),window.addEventListener("load",a,r);else if(document.attachEvent){document.attachEvent("onreadystatechange",l);window.attachEvent("onload",a);var b=r;try{b=window.frameElement==q}catch(n){}document.documentElement.doScroll&&b&&d()}})();return function(d){a.w?d():b.push(d)}}()).w=r;mt.event={};mt.event.d=function(a,d,f){a.attachEvent?a.attachEvent("on"+d,function(b){f.call(a,b)}):a.addEventListener&&a.addEventListener(d,f,r)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=r};mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=f[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function d(a){return 10>a?"0"+a:a}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(b){switch(typeof b){case "undefined":return"undefined";case "number":return isFinite(b)?String(b):"null";case "string":return a(b);case "boolean":return String(b);
default:if(b===q)return"null";if(b instanceof Array){var f=["["],m=b.length,n,e,g;for(e=0;e<m;e++)switch(g=b[e],typeof g){case "undefined":case "function":case "unknown":break;default:n&&f.push(","),f.push(mt.m.stringify(g)),n=1}f.push("]");return f.join("")}if(b instanceof Date)return'"'+b.getFullYear()+"-"+d(b.getMonth()+1)+"-"+d(b.getDate())+"T"+d(b.getHours())+":"+d(b.getMinutes())+":"+d(b.getSeconds())+'"';n=["{"];e=mt.m.stringify;for(m in b)if(Object.prototype.hasOwnProperty.call(b,m))switch(g=
b[m],typeof g){case "undefined":case "unknown":case "function":break;default:f&&n.push(","),f=1,n.push(e(m)+":"+e(g))}n.push("}");return n.join("")}}}();mt.lang={};mt.lang.e=function(a,d){return"[object "+d+"]"==={}.toString.call(a)};mt.lang.Ea=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.Ga=function(a){return mt.lang.e(a,"String")};mt.localStorage={};
mt.localStorage.B=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return r}return p};
mt.localStorage.set=function(a,d,f){var b=new Date;b.setTime(b.getTime()+f||31536E6);try{window.localStorage?(d=b.getTime()+"|"+d,window.localStorage.setItem(a,d)):mt.localStorage.B()&&(mt.localStorage.f.expires=b.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,d),mt.localStorage.f.save(document.location.hostname))}catch(l){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var d=a.indexOf("|"),f=a.substring(0,d)-0;if(f&&f>(new Date).getTime())return a.substring(d+1)}}else if(mt.localStorage.B())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(b){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.B())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,d){if(window.sessionStorage)try{window.sessionStorage.setItem(a,d)}catch(f){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.K={};mt.K.log=function(a,d){var f=new Image,b="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[b]=f;f.onload=f.onerror=f.onabort=function(){f.onload=f.onerror=f.onabort=q;f=window[b]=q;d&&d(a)};f.src=a};mt.A={};
mt.A.ha=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(a=d.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=d.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return a};
mt.A.Z=function(a,d,f,b,l){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+f+'" height="'+b+'"><param name="movie" value="'+d+'" /><param name="flashvars" value="'+(l||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+f+'" height="'+b+'" src="'+d+'" flashvars="'+(l||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.h=function(a,d){var f=a.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return f?f[3]:q};mt.url.Ca=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.ea=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.N=function(a){return(a=mt.url.ea(a))?a.replace(/:\d+$/,""):a};mt.url.Ba=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.p={oa:"http://tongji.baidu.com/hm-web/welcome/ico",S:"hm.baidu.com/hm.gif",W:"baidu.com",la:"hmmd",ma:"hmpl",ka:"hmkw",ia:"hmci",na:"hmsr",n:0,g:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",Fa:0,xa:6E5,ya:10,za:1024,wa:1,o:2147483647,U:"cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={k:{},d:function(a,f){this.k[a]=this.k[a]||[];this.k[a].push(f)},s:function(a,f){this.k[a]=this.k[a]||[];for(var b=this.k[a].length,l=0;l<b;l++)this.k[a][l](f)}};return h.l=a})();
(function(){function a(a,b){var l=document.createElement("script");l.charset="utf-8";d.e(b,"Function")&&(l.readyState?l.onreadystatechange=function(){if("loaded"===l.readyState||"complete"===l.readyState)l.onreadystatechange=q,b()}:l.onload=function(){b()});l.src=a;var m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(l,m)}var d=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?f.set("Hm_from_"+c.id,a):d.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?f.get("Hm_from_"+c.id):d.get("Hm_from_"+c.id))||"";return a}var d=mt.localStorage,f=mt.sessionStorage;return h.L=a})();
(function(){var a=h.p,d=mt.A,f={init:function(){if(""!==c.icon){var b;b=c.icon.split("|");var f=a.oa+"?s="+c.id,m=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+b[0]+"."+b[1];switch(b[1]){case "swf":b=d.Z("HolmesIcon"+a.g,m,b[2],b[3],"s="+f);break;case "gif":b='<a href="'+f+'" target="_blank"><img border="0" src="'+m+'" width="'+b[2]+'" height="'+b[3]+'"></a>';break;default:b='<a href="'+f+'" target="_blank">'+b[0]+"</a>"}document.write(b)}}};h.l.d("pv-b",f.init);return f})();
(function(){var a=mt.q,d=h.p,f=h.load,b=h.L;h.l.d("pv-b",function(){c.rec&&a.T(function(){for(var l=0,m=c.rp.length;l<m;l++){var n=c.rp[l][0],e=c.rp[l][1],g=a.ca("hm_t_"+n);if(e&&!(2==e&&!g||g&&""!==g.innerHTML))g="",g=Math.round(Math.random()*d.o),g=4==e?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+n,"rnd="+g].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+n,"from="+b(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
g].join("&"),f(g)}})})})();(function(){var a=h.p,d=h.load,f=h.L;h.l.d("pv-b",function(){if(c.trust&&c.vcard){var b=a.protocol+"//trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+f(),"rnd="+Math.round(Math.random()*a.o)].join("&");d(b)}})})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.C.fa()+","+h.C.da();h.b.i()}}function d(){clearTimeout(x);var a;w&&(a="visible"==document[w]);y&&(a=!document[y]);e="undefined"==typeof a?p:a;if((!n||!g)&&e&&k)t=p,s=+new Date;else if(n&&g&&(!e||!k))t=r,u+=+new Date-s;n=e;g=k;x=setTimeout(d,100)}function f(a){var g=document,k="";if(a in g)k=a;else for(var s=["webkit","ms","moz","o"],b=0;b<s.length;b++){var e=s[b]+a.charAt(0).toUpperCase()+a.slice(1);if(e in g){k=
e;break}}return k}function b(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))k="focus"==a.type||"focusin"==a.type?p:r,d()}var l=mt.event,m=h.l,n=p,e=p,g=p,k=p,v=+new Date,s=v,u=0,t=p,w=f("visibilityState"),y=f("hidden"),x;d();(function(){var a=w.replace(/[vV]isibilityState/,"visibilitychange");l.d(document,a,d);l.d(window,"pageshow",d);l.d(window,"pagehide",d);"object"==typeof document.onfocusin?(l.d(document,"focusin",b),l.d(document,"focusout",b)):(l.d(window,"focus",b),
l.d(window,"blur",b))})();h.C={fa:function(){return+new Date-v},da:function(){return t?+new Date-s+u:u}};m.d("pv-b",function(){l.d(window,"unload",a())});return h.C})();
(function(){function a(g){for(var k in g)if({}.hasOwnProperty.call(g,k)){var e=g[k];b.e(e,"Object")||b.e(e,"Array")?a(e):g[k]=String(e)}}function d(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var f=mt.K,b=mt.lang,l=mt.m,m=h.p,n=h.l,e={O:q,r:[],z:0,P:r,init:function(){e.c=0;e.O={push:function(){e.I.apply(e,arguments)}};n.d("pv-b",function(){e.$();e.aa()});n.d("pv-d",e.ba);n.d("stag-b",function(){h.b.a.api=e.c||e.z?e.c+"_"+e.z:""});n.d("stag-d",function(){h.b.a.api=
0;e.c=0;e.z=0})},$:function(){var a=window._hmt;if(a&&a.length)for(var k=0;k<a.length;k++){var b=a[k];switch(b[0]){case "_setAccount":1<b.length&&/^[0-9a-z]{32}$/.test(b[1])&&(e.c|=1,window._bdhm_account=b[1]);break;case "_setAutoPageview":if(1<b.length&&(b=b[1],r===b||p===b))e.c|=2,window._bdhm_autoPageview=b}}},aa:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var a=window._hmt;if(a&&a.length)for(var k=0,d=a.length;k<d;k++)b.e(a[k],
"Array")&&"_trackEvent"!==a[k][0]&&"_trackRTEvent"!==a[k][0]?e.I(a[k]):e.r.push(a[k]);window._hmt=e.O}},ba:function(){if(0<e.r.length)for(var a=0,b=e.r.length;a<b;a++)e.I(e.r[a]);e.r=q},I:function(a){if(b.e(a,"Array")){var k=a[0];if(e.hasOwnProperty(k)&&b.e(e[k],"Function"))e[k](a)}},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"==a[1].charAt(0)){e.c|=4;h.b.a.et=0;h.b.a.ep="";h.b.G?(h.b.a.nv=0,h.b.a.st=4):h.b.G=p;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=m.protocol+"//"+document.location.host+
a[1];e.P||(h.b.a.su=document.location.href);h.b.i();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<a.length&&(e.c|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=d(a[1])+"*"+d(a[2])+(a[3]?"*"+d(a[3]):"")+(a[4]?"*"+d(a[4]):""),h.b.i())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],f=a[4]||3;if(0<b&&6>b&&0<f&&4>f){e.z++;for(var s=(h.b.a.cv||"*").split("!"),u=s.length;u<b-1;u++)s.push("*");s[b-1]=f+"*"+d(a[2])+"*"+d(a[3]);h.b.a.cv=s.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.pa("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"==a[1].charAt(0)?m.protocol+"//"+window.location.host+a[1]:a[1],e.P=p)},_trackOrder:function(g){g=g[1];b.e(g,"Object")&&(a(g),e.c|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=l.stringify(g),h.b.i())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])e.c|=32,h.b.a.et=93,h.b.a.ep=a,h.b.i()},_trackRTPageview:function(g){g=
g[1];b.e(g,"Object")&&(a(g),g=l.stringify(g),512>=encodeURIComponent(g).length&&(e.c|=64,h.b.a.rt=g))},_trackRTEvent:function(g){g=g[1];if(b.e(g,"Object")){a(g);g=encodeURIComponent(l.stringify(g));var k=function(a){var b=h.b.a.rt;e.c|=128;h.b.a.et=90;h.b.a.rt=a;h.b.i();h.b.a.rt=b},d=g.length;if(900>=d)k.call(this,g);else for(var d=Math.ceil(d/900),s="block|"+Math.round(Math.random()*m.o).toString(16)+"|"+d+"|",f=[],t=0;t<d;t++)f.push(t),f.push(g.substring(900*t,900*t+900)),k.call(this,s+f.join("|")),
f=[]}},_setUserId:function(a){a=a[1];if(b.e(a,"String")||b.e(a,"Number")){var k=h.b.F(),d="hm-"+h.b.a.v;e.R=e.R||Math.round(Math.random()*m.o);f.log("//datax.baidu.com/x.gif?si="+c.id+"&dm="+encodeURIComponent(k)+"&ac="+encodeURIComponent(a)+"&v="+d+"&li="+e.R+"&rnd="+Math.round(Math.random()*m.o))}}};e.init();h.X=e;return h.X})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.G=r,this.init())}var d=mt.url,f=mt.K,b=mt.A,l=mt.lang,m=mt.cookie,n=mt.j,e=mt.localStorage,g=mt.sessionStorage,k=h.p,v=h.l;a.prototype={H:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var e=a.indexOf(b);return-1<e&&e+b.length==a.length},Q:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},t:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.Q(a,c.dm[b]))return p}else{var e=d.N(a);if(e&&this.H(e,c.dm[b]))return p}return r},F:function(){for(var a=document.location.hostname,b=0,e=c.dm.length;b<e;b++)if(this.H(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},M:function(){for(var a=0,b=c.dm.length;a<b;a++){var e=c.dm[a];if(-1<e.indexOf("/")&&this.Q(document.location.href,e))return e.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},ga:function(){if(!document.referrer)return k.g-k.n>c.vdur?1:4;var a=
r;this.t(document.referrer)&&this.t(document.location.href)?a=p:(a=d.N(document.referrer),a=this.H(a||"",document.location.hostname));return a?k.g-k.n>c.vdur?1:4:3},getData:function(a){try{return m.get(a)||g.get(a)||e.get(a)}catch(b){}},setData:function(a,b,k){try{m.set(a,b,{domain:this.F(),path:this.M(),D:k}),k?e.set(a,b,k):g.set(a,b)}catch(d){}},pa:function(a){try{m.set(a,"",{domain:this.F(),path:this.M(),D:-1}),g.remove(a),e.remove(a)}catch(b){}},ua:function(){var a,b,e,d,g;k.n=this.getData("Hm_lpvt_"+
c.id)||0;13==k.n.length&&(k.n=Math.round(k.n/1E3));b=this.ga();a=4!=b?1:0;if(e=this.getData("Hm_lvt_"+c.id)){d=e.split(",");for(g=d.length-1;0<=g;g--)13==d[g].length&&(d[g]=""+Math.round(d[g]/1E3));for(;2592E3<k.g-d[0];)d.shift();g=4>d.length?2:3;for(1===a&&d.push(k.g);4<d.length;)d.shift();e=d.join(",");d=d[d.length-1]}else e=k.g,d="",g=1;this.setData("Hm_lvt_"+c.id,e,c.age);this.setData("Hm_lpvt_"+c.id,k.g);e=k.g==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.t(document.location.href)&&
(""===document.referrer||this.t(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=e;this.a.lt=d;this.a.lv=g},ta:function(){for(var a=[],b=0,e=k.U.length;b<e;b++){var d=k.U[b],g=this.a[d];"undefined"!=typeof g&&""!==g&&a.push(d+"="+encodeURIComponent(g))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},va:function(){this.ua();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=n.qa;this.a.cl=n.colorDepth+"-bit";
this.a.ln=n.language;this.a.ja=n.javaEnabled?1:0;this.a.ck=n.cookieEnabled?1:0;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=b.ha();this.a.v="1.0.83";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=d.h(a,k.la)||"";this.a.cp=d.h(a,k.ma)||"";this.a.cw=d.h(a,k.ka)||"";this.a.ci=d.h(a,k.ia)||"";this.a.cf=d.h(a,k.na)||""},init:function(){try{this.va(),0===this.a.nv?this.sa():this.J(".*"),h.b=this,this.Y(),
v.s("pv-b"),this.ra()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(k.protocol+"//"+k.S+"?"+b.join("&"))}},ra:function(){function a(){v.s("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.G=p,this.a.et=0,this.a.ep="",this.i(a)):a()},i:function(a){var b=this;b.a.rnd=Math.round(Math.random()*k.o);v.s("stag-b");var e=k.protocol+"//"+
k.S+"?"+b.ta();v.s("stag-d");b.V(e);f.log(e,function(e){b.J(e);l.e(a,"Function")&&a.call(b)})},Y:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),e=-1<document.referrer.indexOf(k.W)?p:r,g=d.h(a,"jn"),f=/^heatlink$|^select$/.test(g);a&&(b.test(a)&&e&&f)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+g+".js?"+this.a.rnd),g=document.getElementsByTagName("script")[0],g.parentNode.insertBefore(a,
g))},V:function(a){var b=g.get("Hm_unsent_"+c.id)||"",e=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+e)+(b?","+b:"");g.set("Hm_unsent_"+c.id,b)},J:function(a){var b=g.get("Hm_unsent_"+c.id)||"";b&&((b=b.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?g.set("Hm_unsent_"+c.id,b):g.remove("Hm_unsent_"+c.id))},sa:function(){var a=this,b=g.get("Hm_unsent_"+
c.id);if(b)for(var b=b.split(","),e=function(b){f.log(k.protocol+"//"+decodeURIComponent(b).replace(/^https?:\/\//,""),function(b){a.J(b)})},d=0,l=b.length;d<l;d++)e(b[d])}};return new a})();
(function(){var a=mt.q,d=mt.event,f=mt.url,b=mt.m;try{if(window.performance&&performance.timing){var l=+new Date,m=function(a){var b=performance.timing,e=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:e,end:a,value:0<a-e?a-e:0}},n=q;a.T(function(){n=+new Date});var e=function(){var a,e,d;d=m("navigation");e=m("request");d={netAll:e.start-d.start,netDns:m("domainLookup").value,netTcp:m("connect").value,srv:m("response").start-e.start,dom:performance.timing.domInteractive-performance.timing.fetchStart,
loadEvent:m("loadEvent").end-d.start};a=document.referrer;var g=q;e=q;if("www.baidu.com"===(a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[])[2])g=f.h(a,"qid"),e=f.h(a,"click_t");a=g;d.qid=a!=q?a:"";e!=q?(d.bdDom=n?n-e:0,d.bdRun=l-e):(d.bdDom=0,d.bdRun=0);h.b.a.et=87;h.b.a.ep=b.stringify(d);h.b.i()};d.d(window,"load",function(){setTimeout(e,500)})}}catch(g){}})();
(function(){if("378f3aa9b8779062c8de4dc247dd8874"===c.id){var a=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},d={click:function(){for(var b=[],d=a(document.getElementsByTagName("a")),d=[].concat.apply(d,a(document.getElementsByTagName("area"))),f=/openZoosUrl\(/,l=0,m=d.length;l<m;l++)f.test(d[l].getAttribute("onclick"))&&b.push(d[l]);return b}},f=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===r)return r},b=function(a,
b){return Object.prototype.toString.call(a)==="[object "+b+"]"};window._hmt=window._hmt||[];var l,m="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),n=function(a,d){if(l===d){window._hmt.push(["_trackPageview",m+a]);for(var f=+new Date;500>=+new Date-f;);return r}if(b(d,"Array")||b(d,"NodeList"))for(var f=0,n=d.length;f<n;f++)if(l===d[f]){window._hmt.push(["_trackPageview",m+a+"/"+(f+1)]);for(f=+new Date;500>=+new Date-f;);return r}};(function(a,b,d){a.addEventListener?a.addEventListener(b,d,p):a.attachEvent&&
a.attachEvent("on"+b,d)})(document,"click",function(a){a=a||window.event;l=a.target||a.srcElement;var g={};for(f(d,function(a,d){g[a]=b(d,"Function")?d():document.getElementById(d)});l&&l!==document&&f(g,n)!==r;)l=l.parentNode})}})();})();
